#+TITLE: Spigot: Rate-limited feed aggregation to pump.io
#+OPTIONS: H:2
Spigot takes syndicated content feeds and posts them to [[http://pump.io/][pump.io]] accounts at a limited rate. This way you can syndicate content to a pump.io account without worrying about flooding the account when updates to the feed are frequent.

First you set up connections to one or more pump.io accounts using OAuth. Then you add RSS or Atom feeds, specifying which account to post to, the maximum post frequency, and the format of the posted message. Each time spigot runs, it checks the feeds for new posts, and determines whether or not a new item should be posted based on the specified interval. Spigot can be run in a cron job (or manually) to make regular posts.

Spigot is inspired by [[https://github.com/zcopley/tricklepost][Tricklepost]] and [[http://brdcst.it/][Brdcst.it]].
** Requirements
*** >= Python 2.6
*** >= [[http://pypi.python.org/pypi/argparse/1.2.1][Argparse]] 1.2.1 (bundled with Python 2.7 or higher)
*** >= [[http://pypi.python.org/pypi/feedparser/5.1.2][Feedparser]] 5.2.1
*** >= [[https://pypi.python.org/pypi/PyPump/][PyPump]] 0.2
** Installation
You can install spigot via pip:

    =$ pip install spigot=

Or if you have cloned the repo, it can be manually installed:

    =$ python setup.py install=

** Running
The first time you run Spigot, it will prompt you to add at least one account and one feed. For further options, pleas run =spigot.py -h=.
** Credits
Spigot is (c) 2011-2013 by [[mailto:nathan@smithfam.info][Nathan D. Smith]].
** License
Spigot is distributed under the terms of the [[http://www.gnu.org/licenses/gpl.html][GNU GPL version 3]] or later.
** FAQ
*** *Where does Spigot store its configuration files and database?*
Spigot stores its configuration (spigot.json) and database (spigot.db) in the working directory from which it is invoked. If you are running Spigot from a cron job, you'll want to first cd into the directory containing these.

*** *How often should I run Spigot?*
There are a couple factors which weigh on this. First, you want to run it often enough so that catches all of the posts in the feeds it is polling. For example, if you are polling a feed which lists 10 items and is updated about 5 times per hour, you need to run Spigot at least every 2 hours to catch all of those posts in its database.

Second, you'll want to run Spigot more often than the shortest interval in your configuration. If you run spigot less often than the shortest interval, posts will effectively happen only as often as Spigot runs.

In brief, Spigot should run more often than you want to actually post.
